// Curated list of countries for search and filters
export const COUNTRIES = [
  "Afrique du Sud",
  "Albanie",
  "Algérie",
  "Allemagne",
  "Argentine",
  "Australie",
  "Autriche",
  "Belgique",
  "Bolivie",
  "Brésil",
  "Bulgarie",
  "Cambodge",
  "Canada",
  "Chili",
  "Chine",
  "Colombie",
  "Corée du Sud",
  "Costa Rica",
  "Croatie",
  "Cuba",
  "Danemark",
  "Égypte",
  "Émirats Arabes Unis",
  "Équateur",
  "Espagne",
  "Estonie",
  "États-Unis",
  "Éthiopie",
  "Finlande",
  "France",
  "Géorgie",
  "Grèce",
  "Guatemala",
  "Hongrie",
  "Île Maurice",
  "Inde",
  "Indonésie",
  "Irlande",
  "Islande",
  "Israël",
  "Italie",
  "Japon",
  "Jordanie",
  "Kenya",
  "Laos",
  "Liban",
  "Madagascar",
  "Malaisie",
  "Maldives",
  "Malte",
  "Maroc",
  "Mexique",
  "Mongolie",
  "Népal",
  "Nicaragua",
  "Norvège",
  "Nouvelle-Zélande",
  "Oman",
  "Pays-Bas",
  "Pérou",
  "Philippines",
  "Pologne",
  "Portugal",
  "République Dominicaine",
  "Roumanie",
  "Royaume-Uni",
  "Russie",
  "Sénégal",
  "Serbie",
  "Seychelles",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Sri Lanka",
  "Suède",
  "Suisse",
  "Tanzanie",
  "Thaïlande",
  "Tunisie",
  "Turquie",
  "Ukraine",
  "Uruguay",
  "Vietnam",
];

export const PLACE_CATEGORIES = [
  { value: "restaurant", label: "Restaurant", emoji: "🍽️" },
  { value: "plage", label: "Plage", emoji: "🏖️" },
  { value: "cascade", label: "Cascade", emoji: "💧" },
  { value: "plongee", label: "Plongée", emoji: "🤿" },
  { value: "hotel", label: "Hôtel", emoji: "🏨" },
  { value: "randonnee", label: "Randonnée", emoji: "🥾" },
  { value: "vie_nocturne", label: "Vie nocturne", emoji: "🌃" },
  { value: "shopping", label: "Shopping", emoji: "🛍️" },
  { value: "pharmacie", label: "Pharmacie", emoji: "💊" },
  { value: "distributeur", label: "Distributeur", emoji: "🏧" },
  { value: "cache", label: "Lieu caché", emoji: "🗝️" },
  { value: "wifi", label: "Wi-Fi", emoji: "📶" },
  { value: "bar", label: "Bar", emoji: "🍹" },
  { value: "musee", label: "Musée", emoji: "🏛️" },
  { value: "activite", label: "Activité", emoji: "🎯" },
  { value: "photospot", label: "Spot photo", emoji: "📸" },
  { value: "event", label: "Événement", emoji: "🎉" },
] as const;

export type PlaceCategory = (typeof PLACE_CATEGORIES)[number]["value"];

export function categoryLabel(cat: string) {
  const c = PLACE_CATEGORIES.find((p) => p.value === cat);
  return c ? `${c.emoji} ${c.label}` : cat;
}
