// @lovable.dev/vite-tanstack-config already includes the core TanStack,
// React, Tailwind, Nitro and path-alias plugins.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

export default defineConfig({
  tanstackStart: {
    server: { entry: "server" },
  },
  vite: {
    server: {
      // Makes the development server reachable from a phone on the same Wi-Fi.
      host: "0.0.0.0",
      port: 5173,
      // Temporary HTTPS preview URLs generated by the calls launcher.
      allowedHosts: [".trycloudflare.com"],
    },
    preview: {
      host: "0.0.0.0",
      port: 4173,
    },
  },
});
