// @lovable.dev/vite-tanstack-config already includes the core TanStack,
// React, Tailwind, Nitro and path-alias plugins.
import { execFileSync } from "node:child_process";
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

// Keep the hotel catalogue strict at dev/build time: a hotel is only visible
// when Booking.com is the verified provider and its photo is Booking-hosted.
execFileSync(process.execPath, ["scripts/apply-booking-hotel-policy.mjs"], {
  stdio: "inherit",
});

export default defineConfig({
  tanstackStart: {
    server: { entry: "server" },
  },
  vite: {
    server: {
      // Makes the development server reachable from a phone on the same Wi-Fi.
      host: "0.0.0.0",
      port: 5173,
      // Temporary HTTPS preview URLs generated by the calls launcher.
      allowedHosts: [".trycloudflare.com"],
    },
    preview: {
      host: "0.0.0.0",
      port: 4173,
    },
  },
});
