/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiProRouteImport } from './routes/ai-pro'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MapRouteImport } from './routes/map'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiTripRouteImport } from './routes/ai-trip'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as QuestionsSlugRouteImport } from './routes/questions.$slug'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as PostIdRouteImport } from './routes/post.$id'
import { Route as MarketplaceIdRouteImport } from './routes/marketplace.$id'
import { Route as DealsSlugRouteImport } from './routes/deals.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ActivitiesSlugRouteImport } from './routes/activities.$slug'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedNewPostRouteImport } from './routes/_authenticated.new-post'
import { Route as AuthenticatedNewPlaceRouteImport } from './routes/_authenticated.new-place'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated.messages'
import { Route as AuthenticatedMatchRouteImport } from './routes/_authenticated.match'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated.achievements'
import { Route as AuthenticatedTripsIndexRouteImport } from './routes/_authenticated.trips.index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated.messages.index'
import { Route as AuthenticatedTripsIdRouteImport } from './routes/_authenticated.trips.$id'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated.settings.profile'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated.security'
import { Route as AuthenticatedMessagesIdRouteImport } from './routes/_authenticated.messages.$id'
import { Route as AuthenticatedMarketplaceNewRouteImport } from './routes/_authenticated.marketplace.new'

const AiProRoute = AiProRouteImport.update({
  id: '/ai-pro',
  path: '/ai-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTripRoute = AiTripRouteImport.update({
  id: '/ai-trip',
  path: '/ai-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsSlugRoute = QuestionsSlugRouteImport.update({
  id: '/questions/$slug',
  path: '/questions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIdRoute = PostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketplaceRoute,
} as any)
const DealsSlugRoute = DealsSlugRouteImport.update({
  id: '/deals/$slug',
  path: '/deals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesSlugRoute = ActivitiesSlugRouteImport.update({
  id: '/activities/$slug',
  path: '/activities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNewPostRoute = AuthenticatedNewPostRouteImport.update({
  id: '/new-post',
  path: '/new-post',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewPlaceRoute = AuthenticatedNewPlaceRouteImport.update({
  id: '/new-place',
  path: '/new-place',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMatchRoute = AuthenticatedMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTripsIndexRoute = AuthenticatedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedTripsIdRoute = AuthenticatedTripsIdRouteImport.update({
  id: '/trips/$id',
  path: '/trips/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesIdRoute = AuthenticatedMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMessagesRoute,
} as any)
const AuthenticatedMarketplaceNewRoute =
  AuthenticatedMarketplaceNewRouteImport.update({
    id: '/marketplace/new',
    path: '/marketplace/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-pro': typeof AiProRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/ai-trip': typeof AiTripRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/match': typeof AuthenticatedMatchRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/new-place': typeof AuthenticatedNewPlaceRoute
  '/new-post': typeof AuthenticatedNewPostRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/api/chat': typeof ApiChatRoute
  '/deals/$slug': typeof DealsSlugRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/deals/': typeof DealsIndexRoute
  '/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/trips/$id': typeof AuthenticatedTripsIdRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/trips/': typeof AuthenticatedTripsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-pro': typeof AiProRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/ai-trip': typeof AiTripRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/match': typeof AuthenticatedMatchRoute
  '/new-place': typeof AuthenticatedNewPlaceRoute
  '/new-post': typeof AuthenticatedNewPostRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/api/chat': typeof ApiChatRoute
  '/deals/$slug': typeof DealsSlugRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/deals': typeof DealsIndexRoute
  '/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/trips/$id': typeof AuthenticatedTripsIdRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/trips': typeof AuthenticatedTripsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-pro': typeof AiProRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ai-trip': typeof AiTripRoute
  '/auth': typeof AuthRoute
  '/map': typeof MapRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/search': typeof SearchRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/match': typeof AuthenticatedMatchRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/new-place': typeof AuthenticatedNewPlaceRoute
  '/_authenticated/new-post': typeof AuthenticatedNewPostRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/activities/$slug': typeof ActivitiesSlugRoute
  '/api/chat': typeof ApiChatRoute
  '/deals/$slug': typeof DealsSlugRoute
  '/marketplace/$id': typeof MarketplaceIdRoute
  '/post/$id': typeof PostIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/questions/$slug': typeof QuestionsSlugRoute
  '/deals/': typeof DealsIndexRoute
  '/_authenticated/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/_authenticated/messages/$id': typeof AuthenticatedMessagesIdRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/trips/$id': typeof AuthenticatedTripsIdRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/trips/': typeof AuthenticatedTripsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-pro'
    | '/forgot-password'
    | '/reset-password'
    | '/api/stripe-webhook'
    | '/ai-trip'
    | '/auth'
    | '/map'
    | '/marketplace'
    | '/search'
    | '/verify-email'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/match'
    | '/messages'
    | '/new-place'
    | '/new-post'
    | '/notifications'
    | '/activities/$slug'
    | '/api/chat'
    | '/deals/$slug'
    | '/marketplace/$id'
    | '/post/$id'
    | '/profile/$username'
    | '/questions/$slug'
    | '/deals/'
    | '/marketplace/new'
    | '/messages/$id'
    | '/settings/profile'
    | '/security'
    | '/trips/$id'
    | '/messages/'
    | '/trips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-pro'
    | '/forgot-password'
    | '/reset-password'
    | '/api/stripe-webhook'
    | '/ai-trip'
    | '/auth'
    | '/map'
    | '/marketplace'
    | '/search'
    | '/verify-email'
    | '/achievements'
    | '/admin'
    | '/dashboard'
    | '/match'
    | '/new-place'
    | '/new-post'
    | '/notifications'
    | '/activities/$slug'
    | '/api/chat'
    | '/deals/$slug'
    | '/marketplace/$id'
    | '/post/$id'
    | '/profile/$username'
    | '/questions/$slug'
    | '/deals'
    | '/marketplace/new'
    | '/messages/$id'
    | '/settings/profile'
    | '/security'
    | '/trips/$id'
    | '/messages'
    | '/trips'
  id:
    | '__root__'
    | '/'
    | '/ai-pro'
    | '/forgot-password'
    | '/reset-password'
    | '/api/stripe-webhook'
    | '/_authenticated'
    | '/ai-trip'
    | '/auth'
    | '/map'
    | '/marketplace'
    | '/search'
    | '/verify-email'
    | '/_authenticated/achievements'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/match'
    | '/_authenticated/messages'
    | '/_authenticated/new-place'
    | '/_authenticated/new-post'
    | '/_authenticated/notifications'
    | '/activities/$slug'
    | '/api/chat'
    | '/deals/$slug'
    | '/marketplace/$id'
    | '/post/$id'
    | '/profile/$username'
    | '/questions/$slug'
    | '/deals/'
    | '/_authenticated/marketplace/new'
    | '/_authenticated/messages/$id'
    | '/_authenticated/settings/profile'
    | '/_authenticated/security'
    | '/_authenticated/trips/$id'
    | '/_authenticated/messages/'
    | '/_authenticated/trips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiProRoute: typeof AiProRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AiTripRoute: typeof AiTripRoute
  AuthRoute: typeof AuthRoute
  MapRoute: typeof MapRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  SearchRoute: typeof SearchRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ActivitiesSlugRoute: typeof ActivitiesSlugRoute
  ApiChatRoute: typeof ApiChatRoute
  DealsSlugRoute: typeof DealsSlugRoute
  PostIdRoute: typeof PostIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  QuestionsSlugRoute: typeof QuestionsSlugRoute
  DealsIndexRoute: typeof DealsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai-pro': {
      id: '/ai-pro'
      path: '/ai-pro'
      fullPath: '/ai-pro'
      preLoaderRoute: typeof AiProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-trip': {
      id: '/ai-trip'
      path: '/ai-trip'
      fullPath: '/ai-trip'
      preLoaderRoute: typeof AiTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/$slug': {
      id: '/questions/$slug'
      path: '/questions/$slug'
      fullPath: '/questions/$slug'
      preLoaderRoute: typeof QuestionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/$id': {
      id: '/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof PostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$id': {
      id: '/marketplace/$id'
      path: '/$id'
      fullPath: '/marketplace/$id'
      preLoaderRoute: typeof MarketplaceIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/deals/$slug': {
      id: '/deals/$slug'
      path: '/deals/$slug'
      fullPath: '/deals/$slug'
      preLoaderRoute: typeof DealsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$slug': {
      id: '/activities/$slug'
      path: '/activities/$slug'
      fullPath: '/activities/$slug'
      preLoaderRoute: typeof ActivitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new-post': {
      id: '/_authenticated/new-post'
      path: '/new-post'
      fullPath: '/new-post'
      preLoaderRoute: typeof AuthenticatedNewPostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new-place': {
      id: '/_authenticated/new-place'
      path: '/new-place'
      fullPath: '/new-place'
      preLoaderRoute: typeof AuthenticatedNewPlaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/match': {
      id: '/_authenticated/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AuthenticatedMatchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trips/': {
      id: '/_authenticated/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthenticatedTripsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/trips/$id': {
      id: '/_authenticated/trips/$id'
      path: '/trips/$id'
      fullPath: '/trips/$id'
      preLoaderRoute: typeof AuthenticatedTripsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/$id': {
      id: '/_authenticated/messages/$id'
      path: '/$id'
      fullPath: '/messages/$id'
      preLoaderRoute: typeof AuthenticatedMessagesIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/marketplace/new': {
      id: '/_authenticated/marketplace/new'
      path: '/marketplace/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof AuthenticatedMarketplaceNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesIdRoute: typeof AuthenticatedMessagesIdRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesIdRoute: AuthenticatedMessagesIdRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMatchRoute: typeof AuthenticatedMatchRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedNewPlaceRoute: typeof AuthenticatedNewPlaceRoute
  AuthenticatedNewPostRoute: typeof AuthenticatedNewPostRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedMarketplaceNewRoute: typeof AuthenticatedMarketplaceNewRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedTripsIdRoute: typeof AuthenticatedTripsIdRoute
  AuthenticatedTripsIndexRoute: typeof AuthenticatedTripsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMatchRoute: AuthenticatedMatchRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedNewPlaceRoute: AuthenticatedNewPlaceRoute,
  AuthenticatedNewPostRoute: AuthenticatedNewPostRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedMarketplaceNewRoute: AuthenticatedMarketplaceNewRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedTripsIdRoute: AuthenticatedTripsIdRoute,
  AuthenticatedTripsIndexRoute: AuthenticatedTripsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceIdRoute: typeof MarketplaceIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceIdRoute: MarketplaceIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiProRoute: AiProRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AiTripRoute: AiTripRoute,
  AuthRoute: AuthRoute,
  MapRoute: MapRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  SearchRoute: SearchRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ActivitiesSlugRoute: ActivitiesSlugRoute,
  ApiChatRoute: ApiChatRoute,
  DealsSlugRoute: DealsSlugRoute,
  PostIdRoute: PostIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  QuestionsSlugRoute: QuestionsSlugRoute,
  DealsIndexRoute: DealsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
