// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import { extractBearerToken } from "@/lib/security";
import type { Database } from "./types";
import { assertSafeSupabasePublishableKey, isOpaqueSupabaseApiKey } from "./key-safety";

// Public Supabase configuration is safe to ship with the app. Keep these fallbacks aligned
// with client.ts so authenticated server functions remain available even if a Vercel
// deployment is missing the public environment variables.
const FALLBACK_SUPABASE_URL = "https://hzsfocphpynxoykfkfaj.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_9Vrha4s7e7HJTQ3euKQyAA_lGjAaSh7";

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isOpaqueSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const request = getRequest();
    if (!request) throw new Error("Unauthorized: No request available");
    const context = await authenticateSupabaseRequest(request);

    return next({
      context,
    });
  },
);

/** Verifies a bearer JWT and returns a user-scoped Supabase client. */
export async function authenticateSupabaseRequest(request: Request) {
  const supabaseUrl = process.env.SUPABASE_URL || FALLBACK_SUPABASE_URL;
  const supabasePublishableKey =
    process.env.SUPABASE_PUBLISHABLE_KEY || FALLBACK_SUPABASE_PUBLISHABLE_KEY;

  assertSafeSupabasePublishableKey(supabasePublishableKey);

  const token = extractBearerToken(request.headers.get("authorization"));

  const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
    global: {
      fetch: createSupabaseFetch(supabasePublishableKey),
      headers: { Authorization: `Bearer ${token}` },
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });

  const { data, error } = await supabase.auth.getClaims(token);
  const userId = typeof data?.claims?.sub === "string" ? data.claims.sub : "";
  if (error || !data?.claims || !userId) {
    throw new Error("Unauthorized: Invalid token");
  }

  return { supabase, userId, claims: data.claims };
}
